spring:
  application:
    name: order-service
  rabbitmq:
    host: 192.168.161.131
    port: 5672
    username: admin
    password: admin
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka

#开启hystrix
feign:
  hystrix:
    enabled: true
    
#暴露端点
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
        
#搭建集群
---
spring:
  profiles: order1
  
server:
  port: 8201
  
---
spring:
  profiles: order2
  
server:
  port: 8202