spring:
  application:
    name: zuul
  rabbitmq:
    host: 192.168.161.131
    port: 5672
    username: admin
    password: admin
    
server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

#如果微服务名称和访问路径一致这部也可以不用配置，如下这种就不用配置
zuul:
  routes:
    item-service: /item-service/**
    user-service: /user-service/**
    order-service: /order-service/**
  #zuul默认有ribbon的负载均衡，但要手动开启ribbon的重试功能  
  retryable: true

#降低 hystrix 超时时间，以便测试降级  
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500

#暴露的监控端点  
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream